[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 4000
  framework = "#custom"
  autoLaunch = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval'; connect-src 'self' https://*.tempolabs.ai https://*.wordpress.com https://*.wp.com https://storage.googleapis.com https://public-api.wordpress.com https://api.openai.com https://generativelanguage.googleapis.com http://localhost:11434 https://*.ollama.ai https://*.supabase.co wss://*.supabase.co https://*.supabase.io https://api.supabase.io https://iyrhkdrblbaiyiftgrhv.supabase.co https://iyrhkdrblbaiyiftgrhv.functions.supabase.co https://iyrhkdrblbaiyiftgrhv.auth.supabase.co; img-src 'self' data: https: blob: https://*.supabase.co; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.tempolabs.ai https://storage.googleapis.com; font-src 'self' data: https://fonts.gstatic.com; frame-src 'self' https://*.supabase.co;"